runtime: php82
service: dev
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|svg|woff2|ttf))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|svg|woff2|ttf)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
env_variables:
  APP_NAME: App
  APP_ENV: development
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  APP_DEBUG: true
